export interface Implementation {
  nombre: string;
  bandera: string;
  producto: string;
  año: string;
  detalle?: string;
}

export const MEMBER_IMPLEMENTATIONS: Record<string, Implementation[]> = {
  "Carlos Cascante": [
    { nombre: "AFP Confía", bandera: "🇸🇻", producto: "Pensiones", año: "1998", detalle: "+1.8M afiliados, $8,219M USD" },
    { nombre: "AFP Crecer", bandera: "🇸🇻", producto: "Pensiones", año: "1998", detalle: "1.5M afiliados, $4,505M USD" },
    { nombre: "RAP", bandera: "🇭🇳", producto: "Pensiones", año: "~2000", detalle: "273,101 afiliados, $1,540M USD" },
    { nombre: "Popular Pensiones", bandera: "🇨🇷", producto: "Pensiones", año: "~2000", detalle: "1,728,132 afiliados" },
    { nombre: "COOPECAR R.L.", bandera: "🇨🇷", producto: "SAF (Cooperativas)", año: "2006" },
    { nombre: "Banco ADOPEM", bandera: "🇩🇴", producto: "Core Bancario", año: "~2006", detalle: "Grupo Fundación Microfinanzas BBVA" },
    { nombre: "MultiMoney", bandera: "🇬🇹🇸🇻🇭🇳🇳🇮🇨🇷", producto: "Banca", año: "2012" },
    { nombre: "Bankaool", bandera: "🇲🇽", producto: "SAF", año: "2013", detalle: "De cooperativa a banco digital 24x7" },
    { nombre: "Broxel", bandera: "🇲🇽", producto: "SAF", año: "2016", detalle: "Primera Fintech Digital en México" },
    { nombre: "ION", bandera: "🇲🇽", producto: "SAF+", año: "2018", detalle: "+1,090 viviendas, +$15 mil MDP" },
    { nombre: "Credicefi", bandera: "🇬🇹", producto: "SAF+", año: "2020" },
    { nombre: "CCSS", bandera: "🇨🇷", producto: "FileMaster", año: "2022", detalle: "+6,120 usuarios, migración a nube" },
    { nombre: "Factor y Valor", bandera: "🇨🇴", producto: "Factoring", año: "2022", detalle: "Factoring para pymes colombianas" },
    { nombre: "Grupo CMI", bandera: "🇬🇹", producto: "SAF+", año: "2025", detalle: "Factoring, Leasing" },
  ],
  "Luis Mangel Alfaro Leal": [
    { nombre: "Banco ADOPEM", bandera: "🇩🇴", producto: "Core Bancario", año: "~2006", detalle: "Grupo Fundación Microfinanzas BBVA" },
    { nombre: "MultiMoney", bandera: "🇬🇹🇸🇻🇭🇳🇳🇮🇨🇷", producto: "Banca", año: "2012", detalle: "Akros como Corporativo Tecnológico" },
    { nombre: "Bankaool", bandera: "🇲🇽", producto: "SAF", año: "2013", detalle: "De cooperativa a banco digital 24x7" },
    { nombre: "Broxel", bandera: "🇲🇽", producto: "SAF", año: "2016", detalle: "Primera Fintech Digital en México" },
    { nombre: "ION", bandera: "🇲🇽", producto: "SAF+", año: "2018", detalle: "+1,090 viviendas" },
    { nombre: "Credicefi", bandera: "🇬🇹", producto: "SAF+", año: "2020" },
    { nombre: "Factor y Valor", bandera: "🇨🇴", producto: "Factoring", año: "2022" },
    { nombre: "Grupo Apex", bandera: "🇬🇹🇸🇻🇭🇳🇳🇮🇨🇷🇵🇦", producto: "SAF+", año: "2025" },
    { nombre: "Arkfin Soluciones", bandera: "🇬🇹🇸🇻🇭🇳🇳🇮🇨🇷🇵🇦", producto: "SAF+", año: "2025" },
  ],
  "María Nelly Vargas Salazar": [
    { nombre: "MultiMoney", bandera: "🇬🇹🇸🇻🇭🇳🇳🇮🇨🇷", producto: "Banca", año: "2012" },
    { nombre: "Bankaool", bandera: "🇲🇽", producto: "SAF", año: "2013" },
    { nombre: "Financiera MVA", bandera: "🇬🇹", producto: "Core Bancario", año: "2014", detalle: "PyMEs guatemaltecas" },
    { nombre: "Broxel", bandera: "🇲🇽", producto: "SAF", año: "2016" },
    { nombre: "ION", bandera: "🇲🇽", producto: "SAF+", año: "2018" },
    { nombre: "SOFIMSA", bandera: "🇨🇷", producto: "SAF+", año: "2020", detalle: "Factoring en Azure" },
    { nombre: "Credicefi", bandera: "🇬🇹", producto: "SAF+", año: "2020" },
    { nombre: "Factor y Valor", bandera: "🇨🇴", producto: "Factoring", año: "2022" },
    { nombre: "AMC", bandera: "🇸🇻", producto: "SAF+", año: "2025" },
    { nombre: "Dos Pinos", bandera: "🇨🇷", producto: "SAF+", año: "2025", detalle: "+200 puntos de venta" },
    { nombre: "Grupo CMI", bandera: "🇬🇹", producto: "SAF+", año: "2025", detalle: "Factoring, Leasing" },
  ],
  "Olga Lucia Cuervo Restrepo": [
    { nombre: "Banco ADOPEM", bandera: "🇩🇴", producto: "Core Bancario", año: "~2006" },
    { nombre: "MultiMoney", bandera: "🇬🇹🇸🇻🇭🇳🇳🇮🇨🇷", producto: "Banca", año: "2012" },
    { nombre: "Bankaool", bandera: "🇲🇽", producto: "SAF", año: "2013" },
    { nombre: "Broxel", bandera: "🇲🇽", producto: "SAF", año: "2016" },
    { nombre: "ION", bandera: "🇲🇽", producto: "SAF+", año: "2018" },
    { nombre: "SOFIMSA", bandera: "🇨🇷", producto: "SAF+", año: "2020" },
    { nombre: "Credicefi", bandera: "🇬🇹", producto: "SAF+", año: "2020" },
    { nombre: "CCSS", bandera: "🇨🇷", producto: "FileMaster", año: "2022" },
    { nombre: "Factor y Valor", bandera: "🇨🇴", producto: "Factoring", año: "2022" },
  ],
  "Jhonny Brenes": [
    { nombre: "SOFIMSA", bandera: "🇨🇷", producto: "SAF+", año: "2020" },
    { nombre: "Credicefi", bandera: "🇬🇹", producto: "SAF+", año: "2020" },
    { nombre: "CCSS", bandera: "🇨🇷", producto: "FileMaster", año: "2022" },
    { nombre: "Factor y Valor", bandera: "🇨🇴", producto: "Factoring", año: "2022" },
    { nombre: "AMC", bandera: "🇸🇻", producto: "SAF+", año: "2025" },
    { nombre: "Grupo CMI", bandera: "🇬🇹", producto: "SAF+", año: "2025", detalle: "Factoring, Leasing" },
    { nombre: "Dos Pinos", bandera: "🇨🇷", producto: "SAF+", año: "2025", detalle: "+200 puntos de venta" },
    { nombre: "Grupo Apex", bandera: "🇬🇹🇸🇻🇭🇳🇳🇮🇨🇷🇵🇦", producto: "SAF+", año: "2025" },
  ],
  "Fernando Pinto": [
    { nombre: "MultiMoney", bandera: "🇬🇹🇸🇻🇭🇳🇳🇮🇨🇷", producto: "Banca", año: "2012" },
    { nombre: "Bankaool", bandera: "🇲🇽", producto: "SAF", año: "2013" },
    { nombre: "Broxel", bandera: "🇲🇽", producto: "SAF", año: "2016", detalle: "Primera Fintech Digital en México" },
    { nombre: "ION", bandera: "🇲🇽", producto: "SAF+", año: "2018" },
    { nombre: "Credicefi", bandera: "🇬🇹", producto: "SAF+", año: "2020" },
    { nombre: "CCSS", bandera: "🇨🇷", producto: "FileMaster", año: "2022" },
    { nombre: "Factor y Valor", bandera: "🇨🇴", producto: "Factoring", año: "2022" },
    { nombre: "Grupo CMI", bandera: "🇬🇹", producto: "SAF+", año: "2025" },
  ],
  "Julian Gómez": [
    { nombre: "Banco ADOPEM", bandera: "🇩🇴", producto: "Core Bancario", año: "~2006" },
    { nombre: "Bankaool", bandera: "🇲🇽", producto: "SAF", año: "2013" },
    { nombre: "Broxel", bandera: "🇲🇽", producto: "SAF", año: "2016" },
    { nombre: "ION", bandera: "🇲🇽", producto: "SAF+", año: "2018" },
    { nombre: "SOFIMSA", bandera: "🇨🇷", producto: "SAF+", año: "2020" },
    { nombre: "Credicefi", bandera: "🇬🇹", producto: "SAF+", año: "2020" },
    { nombre: "Factor y Valor", bandera: "🇨🇴", producto: "Factoring", año: "2022" },
    { nombre: "Grupo Apex", bandera: "🇬🇹🇸🇻🇭🇳🇳🇮🇨🇷🇵🇦", producto: "SAF+", año: "2025" },
  ],
  "Dennis García": [
    { nombre: "MultiMoney", bandera: "🇬🇹🇸🇻🇭🇳🇳🇮🇨🇷", producto: "Banca", año: "2012" },
    { nombre: "Bankaool", bandera: "🇲🇽", producto: "SAF", año: "2013" },
    { nombre: "Broxel", bandera: "🇲🇽", producto: "SAF", año: "2016" },
    { nombre: "ION", bandera: "🇲🇽", producto: "SAF+", año: "2018" },
    { nombre: "SOFIMSA", bandera: "🇨🇷", producto: "SAF+", año: "2020" },
    { nombre: "Credicefi", bandera: "🇬🇹", producto: "SAF+", año: "2020" },
    { nombre: "CCSS", bandera: "🇨🇷", producto: "FileMaster", año: "2022" },
    { nombre: "Factor y Valor", bandera: "🇨🇴", producto: "Factoring", año: "2022" },
    { nombre: "AMC", bandera: "🇸🇻", producto: "SAF+", año: "2025" },
  ],
  "Javier Acuña": [
    { nombre: "MultiMoney", bandera: "🇬🇹🇸🇻🇭🇳🇳🇮🇨🇷", producto: "Banca", año: "2012" },
    { nombre: "Factor y Valor", bandera: "🇨🇴", producto: "Factoring", año: "2012" },
    { nombre: "Bankaool", bandera: "🇲🇽", producto: "SAF", año: "2013" },
    { nombre: "Financiera MVA", bandera: "🇬🇹", producto: "Core Bancario", año: "2014" },
    { nombre: "Broxel", bandera: "🇲🇽", producto: "SAF", año: "2016" },
    { nombre: "ION", bandera: "🇲🇽", producto: "SAF+", año: "2018" },
    { nombre: "Credicefi", bandera: "🇬🇹", producto: "SAF+", año: "2020" },
    { nombre: "Factor y Valor", bandera: "🇨🇴", producto: "Factoring", año: "2022" },
  ],
  "Martin Pisacreta": [
    { nombre: "ION", bandera: "🇲🇽", producto: "SAF+", año: "2018" },
    { nombre: "SOFIMSA", bandera: "🇨🇷", producto: "SAF+", año: "2020" },
    { nombre: "Credicefi", bandera: "🇬🇹", producto: "SAF+", año: "2020" },
    { nombre: "CCSS", bandera: "🇨🇷", producto: "FileMaster", año: "2022" },
    { nombre: "Factor y Valor", bandera: "🇨🇴", producto: "Factoring", año: "2022" },
    { nombre: "AMC", bandera: "🇸🇻", producto: "SAF+", año: "2025" },
    { nombre: "Grupo CMI", bandera: "🇬🇹", producto: "SAF+", año: "2025" },
    { nombre: "Arkfin Soluciones", bandera: "🇬🇹🇸🇻🇭🇳🇳🇮🇨🇷🇵🇦", producto: "SAF+", año: "2025" },
  ],
  "Orlando Castro": [
    { nombre: "COOPECAR R.L.", bandera: "🇨🇷", producto: "SAF (Cooperativas)", año: "2006" },
    { nombre: "Banco ADOPEM", bandera: "🇩🇴", producto: "Core Bancario", año: "~2006", detalle: "Grupo Fundación Microfinanzas BBVA" },
    { nombre: "Factor y Valor", bandera: "🇨🇴", producto: "Factoring", año: "2012", detalle: "Factoring para pymes" },
    { nombre: "MultiMoney", bandera: "🇬🇹🇸🇻🇭🇳🇳🇮🇨🇷", producto: "Banca", año: "2012" },
    { nombre: "Bankaool", bandera: "🇲🇽", producto: "SAF", año: "2013" },
    { nombre: "Broxel", bandera: "🇲🇽", producto: "SAF", año: "2016" },
    { nombre: "ION", bandera: "🇲🇽", producto: "SAF+", año: "2018" },
    { nombre: "SOFIMSA", bandera: "🇨🇷", producto: "SAF+ Factoring", año: "2020", detalle: "Factoring en Azure" },
    { nombre: "Credicefi", bandera: "🇬🇹", producto: "SAF+", año: "2020" },
    { nombre: "Factor y Valor", bandera: "🇨🇴", producto: "Factoring", año: "2022" },
    { nombre: "AMC", bandera: "🇸🇻", producto: "SAF+", año: "2025" },
    { nombre: "Grupo CMI", bandera: "🇬🇹", producto: "SAF+", año: "2025", detalle: "Factoring, Leasing" },
    { nombre: "Dos Pinos", bandera: "🇨🇷", producto: "SAF+", año: "2025", detalle: "+200 puntos de venta" },
  ],
  "Alexander Avila": [
    { nombre: "SOFIMSA", bandera: "🇨🇷", producto: "SAF+", año: "2020" },
    { nombre: "Credicefi", bandera: "🇬🇹", producto: "SAF+", año: "2020" },
    { nombre: "CCSS", bandera: "🇨🇷", producto: "FileMaster", año: "2022" },
    { nombre: "Factor y Valor", bandera: "🇨🇴", producto: "Factoring", año: "2022" },
    { nombre: "AMC", bandera: "🇸🇻", producto: "SAF+", año: "2025" },
    { nombre: "Grupo CMI", bandera: "🇬🇹", producto: "SAF+", año: "2025" },
    { nombre: "Dos Pinos", bandera: "🇨🇷", producto: "SAF+", año: "2025" },
    { nombre: "Grupo Apex", bandera: "🇬🇹🇸🇻🇭🇳🇳🇮🇨🇷🇵🇦", producto: "SAF+", año: "2025" },
  ],
  "Lucas Julián Sain": [
    { nombre: "AFP Habitat", bandera: "🇨🇱", producto: "Pensiones", año: "~2000", detalle: "587,097 afiliados" },
    { nombre: "República AFAP", bandera: "🇺🇾", producto: "Pensiones", año: "~2000", detalle: "1.6M afiliados, $22,000M USD" },
    { nombre: "Popular Pensiones", bandera: "🇨🇷", producto: "Pensiones", año: "~2000", detalle: "1,728,132 afiliados" },
    { nombre: "Banorte Pensiones", bandera: "🇲🇽", producto: "Pensiones", año: "~2002", detalle: "12M afiliados" },
    { nombre: "MetLife Pensiones", bandera: "🇲🇽", producto: "Pensiones", año: "~2002", detalle: "698,784 afiliados" },
    { nombre: "Bankaool", bandera: "🇲🇽", producto: "SAF", año: "2013" },
    { nombre: "Broxel", bandera: "🇲🇽", producto: "SAF", año: "2016" },
    { nombre: "ION", bandera: "🇲🇽", producto: "SAF+", año: "2018" },
    { nombre: "Credicefi", bandera: "🇬🇹", producto: "SAF+", año: "2020" },
    { nombre: "CCSS", bandera: "🇨🇷", producto: "FileMaster", año: "2022", detalle: "Migración a nube" },
    { nombre: "Factor y Valor", bandera: "🇨🇴", producto: "Factoring", año: "2022" },
  ],
  "Carlos Andrés Solís Sequeira": [
    { nombre: "RAP", bandera: "🇭🇳", producto: "Pensiones", año: "~2000", detalle: "273,101 afiliados" },
    { nombre: "AFP Atlántida", bandera: "🇭🇳", producto: "Pensiones", año: "~2000", detalle: "78,000 afiliados" },
    { nombre: "AFPC Occidente", bandera: "🇭🇳", producto: "Pensiones", año: "~2000", detalle: "82,539 afiliados" },
    { nombre: "AFP Atlántico", bandera: "🇭🇳", producto: "Pensiones", año: "~2000", detalle: "104,047 afiliados" },
    { nombre: "Bankaool", bandera: "🇲🇽", producto: "SAF", año: "2013" },
    { nombre: "Broxel", bandera: "🇲🇽", producto: "SAF", año: "2016" },
    { nombre: "ION", bandera: "🇲🇽", producto: "SAF+", año: "2018" },
    { nombre: "Credicefi", bandera: "🇬🇹", producto: "SAF+", año: "2020" },
    { nombre: "CCSS", bandera: "🇨🇷", producto: "FileMaster", año: "2022" },
    { nombre: "Factor y Valor", bandera: "🇨🇴", producto: "Factoring", año: "2022" },
  ],
  "Danilo Vezzoni": [
    { nombre: "MultiMoney", bandera: "🇬🇹🇸🇻🇭🇳🇳🇮🇨🇷", producto: "Banca", año: "2012" },
    { nombre: "Bankaool", bandera: "🇲🇽", producto: "SAF", año: "2013" },
    { nombre: "Broxel", bandera: "🇲🇽", producto: "SAF", año: "2016" },
    { nombre: "ION", bandera: "🇲🇽", producto: "SAF+", año: "2018" },
    { nombre: "SOFIMSA", bandera: "🇨🇷", producto: "SAF+", año: "2020" },
    { nombre: "Credicefi", bandera: "🇬🇹", producto: "SAF+", año: "2020" },
    { nombre: "CCSS", bandera: "🇨🇷", producto: "FileMaster", año: "2022" },
    { nombre: "Factor y Valor", bandera: "🇨🇴", producto: "Factoring", año: "2022" },
    { nombre: "AMC", bandera: "🇸🇻", producto: "SAF+", año: "2025" },
    { nombre: "Grupo CMI", bandera: "🇬🇹", producto: "SAF+", año: "2025" },
  ],
};
